### ISSUE TITLE
Problem verifying with Arduino Nano Every - resolved

### ISSUE THREAD

**Issue by cst555** [icomedit/Arduino-KIMlib#2]
I'm new to Github so I'm sorry if I do this wrong...

I tried to verify the Helloworld project to load into an Arduino Nano Every but it threw an error while trying to verify.  It did this with other example projects too.

**To Reproduce**
1. Go to 'KIMlib > Examples > Helloworld'
2. Click on 'Verify'
3. Saw error regarding `uint16_t float2half` and `long m = round(v) & 0x7FF;`

I expected that the project would verify.

Sorry I did not take any screenshot.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.6.4
 - Browser: Chrome
 - Version: Version 99.0.4844.84 (Official Build) (x86_64)

After some googling about this error I found that by changing line 461 in KIMlib.cpp from:
`long m = round(v) & 0x7FF;`
to this:
`long m = ((int)round(v)) & 0x7FF;`
resolved the problem and I was able to verify and upload the Helloworld project.

**Comment by icomedit** [comment]
I tried to reproduce the issue in my lab with Arduino IDE v. 1.8.13 and I selected board "Arduino Nano", but the verify is ok.
I suggest you to use the Analog example to test the effect of conversion run on Arduino Uno with KIMaip KNX/EIB shield. 
Stay tuned.
